booking:
  property: "Booking Profile Dev Updated"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bookingdb"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true